# Generated by Django 3.2.17 on 2023-02-09 11:12

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('symbol', models.CharField(max_length=8, unique=True)),
                ('shortname', models.CharField(max_length=64)),
                ('longname', models.CharField(max_length=128)),
                ('current_price', models.FloatField()),
                ('marketcap', models.BigIntegerField()),
                ('ebitda', models.BigIntegerField()),
                ('revenue_growth', models.FloatField()),
                ('full_time_employees', models.IntegerField()),
                ('long_business_summary', models.TextField()),
                ('weight', models.FloatField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.cities')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.exchanges')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.industries')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
