# Generated by Django 3.2.17 on 2023-02-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20230210_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.states'),
        ),
        migrations.AlterField(
            model_name='states',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.countries'),
        ),
    ]
