# Generated by Django 3.2.17 on 2023-02-11 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20230211_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.countries'),
        ),
    ]
