# Generated by Django 3.2.17 on 2023-02-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_cities_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
