# Generated by Django 3.2.17 on 2023-02-11 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_cities_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.cities'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='industry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.industries'),
        ),
    ]
